import { type RouteConfig, route } from "@react-router/dev/routes";

export default [
  route("/",              "routes/index.tsx"),
  route("/login",         "routes/login.tsx"),
  route("/register",      "routes/register.tsx"),
  route("/home",          "routes/home.tsx"),
  route("/crear",         "routes/crear.tsx"),
  route("/matchmaking",   "routes/matchmaking.tsx"),
  route("/perfil",        "routes/perfil.tsx"),
  route("/perfil/editar",        "routes/perfil.editar.tsx"),
  route("/perfil/mmr-historial", "routes/perfil.mmr-historial.tsx"),
  route("/ranking",          "routes/ranking.tsx"),
  route("/forgot-password",  "routes/forgot-password.tsx"),
  route("/reset-password",   "routes/reset-password.tsx"),
  route("/matches/:id",      "routes/match.$id.tsx"),
  route("/admin/login",           "routes/admin.login.tsx"),
  route("/admin",                 "routes/admin.tsx"),
  route("/admin/usuarios",        "routes/admin.usuarios.tsx"),
  route("/admin/usuarios/:id",    "routes/admin.usuario.$id.tsx"),
  route("/admin/partidos",        "routes/admin.partidos.tsx"),
  route("/admin/partidos/:id",    "routes/admin.partido.$id.tsx"),
  route("/admin/backup",          "routes/admin.backup.tsx"),
  route("/admin/metricas",        "routes/admin.metricas.tsx"),
  route("/admin/auditoria",       "routes/admin.auditoria.tsx"),
  route("/notificaciones",        "routes/notificaciones.tsx"),
] satisfies RouteConfig;
